[tool.poetry]
name = "weather"
version = "0.1.0"
description = "Simple weather microservice in FastAPI."
authors = ["mirek <mirek@cnl.sk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = { extras = ["standard"], version = "^0.115.6" }
pydantic-settings = "^2.6.1"
apscheduler = "^3.11.0"
sqlmodel = "^0.0.22"
sqladmin = "^0.20.1"
pendulum = "^3.0.0"
fastapi-pagination = "^0.12.32"


[tool.poetry.group.dev.dependencies]
ipython = "^8.30.0"
httpie = "^3.2.4"
litecli = "^1.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
