[tool.poetry]
name = "weather"
version = "0.1.0"
description = "The weather microservice."
authors = ["Miroslav Biňas <miroslav.binas@tuke.sk>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

#[tool.poetry.scripts]
#pokedex="weather.main:main"  # python -m weather.main

