[tool.poetry]
name = "pokedex"
version = "0.1.0"
description = "The web based Pokédex implementation in Python."
authors = ["Miroslav Biňas <miroslav.binas@tuke.sk>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.99.1"
uvicorn = "^0.22.0"


[tool.poetry.group.dev.dependencies]
ipython = "^8.14.0"
httpie = "^3.2.2"
litecli = "^1.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
